package com.advancedraidtracker.utility;

public class ItemReference
{

    public static String[][] ITEMS = {
            {"none", "elite void", "void knight", "fury", "barrows gloves"},
            {
                    "torva",
					"avernic treads",
                    "defender",
                    "scythe",
                    "osmumten",
                    "blade",
                    "halberd",
                    "melee",
                    "dagger",
                    "inquisitor",
                    "claws",
                    "rapier",
                    "bulwark",
                    "hammer",
                    "primordial",
                    "ferocious",
                    "infernal",
                    "fire cape",
					"fire max cape",
                    "bandos",
                    "godsword",
                    "dragon boots",
                    "whip",
                    "tentacle",
                    "salve",
                    "faceguard",
                    "torso",
                    "joint",
                    "torture",
                    "serpentine helm",
                    "voidwaker",
                    "keris",
                    "barrows",
                    "tanzanite",
					"magma",
					"goblin paint cannon",
					"strength",
					"combat bracelet",
					"rancour",
					"anchor",
					"blood moon",
					"dharok",
					"oathplate",
					"tecpatl"
            },
            {
                    "masori",
					"avernic treads",
                    "bow",
                    "range",
                    "blowpipe",
					"armadyl chestplate",
					"armadyl chainskirt",
					"armadyl helmet",
                    "anguish",
                    "assembler",
                    "pegasian",
                    "buckler",
                    "chinchompa",
                    "vambraces",
                    "crystal",
                    "darts",
                    "quiver",
                    "eclipse",
                    "ralos",
					"dizana"
            },
            {
                    "ancestral",
					"avernic treads",
                    "virtus",
                    "occult",
                    "tormented",
					"confliction",
                    "tumeken",
                    "staff",
                    "mage",
                    "eternal",
                    "imbued",
                    "trident",
                    "kodai",
                    "ice",
                    "ward",
                    "dawnbringer",
					"ayak",
					"ancient sceptre"
            }
    };
    public static final int MELEE = 1;
    public static final int RANGE = 2;
    public static final int MAGE = 3;
    public static final int NONE = 0;
}
